---
dist: bionic
language: python
python: "3.9"
os: linux
services:
  - docker
env:
  jobs:
    - MOLECULE_DISTRO=debian:stretch-slim
    - MOLECULE_DISTRO=debian:buster-slim
    - MOLECULE_DISTRO=debian:bullseye-slim
install:
  - pip install pipenv
  - pipenv sync
script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
